spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=master;encrypt=true;trustServerCertificate=true
    username: sa
    password: justinzhang515

server:
  port: 9090

logging:
  level:
    web: debug

mybatis:
  type-aliases-package: com.library.springboot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
